# Site settings
title: 前端外刊评论
SEOTitle: 前端外刊评论-翻译 前端 前端开发 JavaScript Angular jQuery React Node.js 互联网
header-img: http://7xrvqo.com1.z0.glb.clouddn.com/images/great-frontend.9d9e3846.png
email: island205@gmail.com
description: ""
keyword: ""
url: "http://qianduan.guru"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

author_list: [
  寸志,
  范洪春,
  kmokidd,
  姜天意,
  橙子,
  张轩,
  李凌豪,
  黄玄,
  MrSunny,
  追客
]

authors:
  寸志:
    name: 寸志
    display_name: 寸志
    avatar: http://7xrvqo.com1.z0.glb.clouddn.com/images/avatars/cunzhi.d4b31d0f.jpg
    email: island205@gmail.com
    web: http://island205.github.io
    twitter: island205
    company: 陆金所
    position: 前端架构师
    github: island205
    weibo: chromeappsstore
  范洪春:
    name: 范洪春
    display_name: 范洪春
    avatar: http://7xrvqo.com1.z0.glb.clouddn.com/images/avatars/fanhongchun.07138240.jpg
    email: fanhc019@gmail.com
    web: https://www.zhihu.com/people/fanhc
    twitter:
    company: 阿里巴巴
    position: 高级前端工程师
    github: fanhc019
    weibo: fanhc019
  kmokidd:
    name: kmokidd
    display_name: 何语萱
    avatar: http://7xrvqo.com1.z0.glb.clouddn.com/images/avatars/kmokidd.d5ef6fa1.jpg
    email: kmokidd@gmail.com
    web:
    twitter: kmokidd
    company: 腾讯ISUX
    position: UI工程师
    github: kmokidd
    weibo:
  姜天意:
    name: 姜天意
    display_name: 99
    avatar: http://7xrvqo.com1.z0.glb.clouddn.com/images/avatars/jtyjty99999.e310947f.jpg
    email: jtyjty99999@126.com
    web: http://99jty.com
    twitter:
    company: 阿里巴巴
    position: Node.js 工程师
    github: jtyjty99999
    weibo:
  MrSunny:
    name: MrSunny
    display_name: MrSunny
    avatar: http://7xrvqo.com1.z0.glb.clouddn.com/images/avatars/MrSunny.d7aa3379.jpg
    email:
    web: https://www.zhihu.com/people/mrsunny
    twitter:
    company: 阿里巴巴
    position: 前端工程师
    github:
    weibo:
  橙子:
    name: 橙子
    display_name: 李金成
    avatar: http://7xrvqo.com1.z0.glb.clouddn.com/images/avatars/chenzi.57547cf3.jpg
    email: lylijincheng@hotmail.com
    web: http://lylijincheng.herokuapp.com/blog
    twitter: lylijincheng
    company: 美柚
    position: Web 工程师
    github: lylijincheng
    weibo:
  张轩:
    name: 张轩
    display_name: 张轩
    avatar: http://7xrvqo.com1.z0.glb.clouddn.com/images/avatars/vikingmute.3ceecea1.jpg
    email:
    web: http://vikingmute.com/
    twitter:
    company: 苹果公司
    position: 前端工程师
    github: vikingmute
    weibo: vikingmute
  李凌豪:
    name: 李凌豪
    display_name: 李凌豪
    avatar: http://7xrvqo.com1.z0.glb.clouddn.com/images/avatars/llh911001.6aa6c3e2.jpg
    email: llh911001@gmail.com
    web: http://hackll.com
    twitter: lilh42
    company: 阿里巴巴
    position: 资深前端工程师
    github: llh911001
  黄玄:
    name: 黄玄
    display_name: 黄玄
    avatar: http://7xrvqo.com1.z0.glb.clouddn.com/images/avatars/hux.e4c0d069.jpg
    email: huxpro@gmail.com
    web: http://huangxuan.me
    twitter: huxpro
    company: 微信电影票
    position: 高级前端工程师
    github: huxpro
    weibo:  huxpro
  追客:
    name: 梁远成
    display_name: 追客
    avatar: http://7xrvqo.com1.z0.glb.clouddn.com/images/avatars/drake.ab896153.png
    email: drakeleung42@gmail.com
    web: http://drakeleung.github.io/blog/
    twitter: DrakeLeung
    company: 无
    position: 前端魔法师
    github: DrakeLeung
    weibo:  DrakeLeung


# SNS settings
RSS: true
weibo_username:     5368192199
zhihu:     http://zhuanlan.zhihu.com/FrontendMagazine
github_username:    FrontendMagazine



# Build settings
highlighter: rouge #pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", 'src', 'dist', 'contribution']
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: fronteer
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-74788760-1'            # Format: UA-xxxxxx-xx
ga_domain: qianduan.guru



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "欢迎关注「前端外刊评论」公众号——关注前端前沿技术，探寻业界深邃思想。"
sidebar-avatar: http://7xrvqo.com1.z0.glb.clouddn.com/images/wechat-qrcode.ac648ab0.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
  {
    title: '黄玄的博客',
    href: 'http://huangxuan.me/'
  },
  {
    title: '敏捷大拇指',
    href: 'http://www.swifthumb.com/'
  }
]

gems: ['jekyll-paginate']
